
import App from '../../components/app/app'
import Header from '../../components/header/header'
import { AuthProvider } from '../../context/authContext'
import { NotificationProvider } from '../../context/notifyContext'
import './globals.css'
import { Inter, Noticia_Text } from 'next/font/google'
import SideBar from '../../components/sidebar/sidebar'
import { Box } from '@mui/material'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{backgroundColor: '#f7f7f7'}}>

          <NotificationProvider>
            <AuthProvider>
              <App>
                <Header />
                <SideBar />
                <Box ml={'80px'} mt={'20px'}>
                  {children} 
                </Box>
              </App>
            </AuthProvider>
          </NotificationProvider>
        
      </body>
    </html>
  )
}
